// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQYQPOOOOQO'#Ch'#ChOOQO'#Ce'#CeQYQPOOOOQO-E6c-E6c",
  stateData: "p~OPOSQOS~OSPOTPOUPOVPOWPO~OUWVW~",
  goto: "h]PPPPPPPPP^PPdQRORSRTQOR",
  nodeNames: "⚠ Comment Space Program Auto Boolean Integer Float Length",
  maxTerm: 12,
  skippedNodes: [0,1,2],
  repeatNodeCount: 1,
  tokenData: "(n~R`X^!Tpq!T!P!Q!x!Q!R#g!R![%l#T#U'[#Y#Z's#h#i(b#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!YYQ~X^!Tpq!T#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!{P!P!Q#O~#TSP~OY#OZ;'S#O;'S;=`#a<%lO#O~#dP;=`<%l#O~#lWU~!O!P$U!Q![%l#V#W$x#X#Y$U#]#^&W#a#b$x#d#e&^#l#m&d~$XQ!Q!R$_!R![$m~$dRV~!Q![$m#X#Y$x#l#m%T~$rQV~!Q![$m#X#Y$x~${P#a#b%O~%TOW~~%WP!Q![%Z~%^P#T#Z%a~%fQV~!Q![%Z#X#Y$x~%qVU~!O!P$U!Q![%l#V#W$x#X#Y$U#]#^&W#a#b$x#d#e&^~&ZP#b#c%O~&aP#h#i%O~&gP!Q![&j~&mP#T#Z&p~&uVU~!O!P$U!Q![&j#V#W$x#X#Y$U#]#^&W#a#b$x#d#e&^~'_P#i#j'b~'eP#h#i'h~'kP#c#d'n~'sOS~~'vP#T#U'y~'|P#`#a(P~(SP#g#h(V~(YP#X#Y(]~(bOT~~(eP#f#g(h~(kP#i#j(V",
  tokenizers: [0],
  topRules: {"Program":[0,3]},
  tokenPrec: 27
})
