// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Space = 2,
  Program = 3,
  Auto = 4,
  Boolean = 5,
  Integer = 6,
  Float = 7,
  Length = 8
