// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,auto:28, true:30, false:30}
export const parser = LRParser.deserialize({
  version: 14,
  states: "zQYQPOOOOQO'#C_'#C_OOQO'#Ca'#CaOOQO'#Ci'#CiOOQO'#Ce'#CeQYQPOOOOQO-E6c-E6c",
  stateData: "s~OPOS[OS~OSROUROVROWRO^PO_QO~OWVUV~",
  goto: "m^PPP_P_PPPcPPPiTROTQTORUTTSOT",
  nodeNames: "⚠ Comment Program Auto Identifier Boolean Integer Float Length",
  maxTerm: 15,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "'j~R`X^!Tpq!T!P!Q!x!Q!R#g!R![%l!c!}'[#R#S'[#T#o'[#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!YY[~X^!Tpq!T#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!{P!P!Q#O~#TSP~OY#OZ;'S#O;'S;=`#a<%lO#O~#dP;=`<%l#O~#lWU~!O!P$U!Q![%l#V#W$x#X#Y$U#]#^&W#a#b$x#d#e&^#l#m&d~$XQ!Q!R$_!R![$m~$dRV~!Q![$m#X#Y$x#l#m%T~$rQV~!Q![$m#X#Y$x~${P#a#b%O~%TOW~~%WP!Q![%Z~%^P#T#Z%a~%fQV~!Q![%Z#X#Y$x~%qVU~!O!P$U!Q![%l#V#W$x#X#Y$U#]#^&W#a#b$x#d#e&^~&ZP#b#c%O~&aP#h#i%O~&gP!Q![&j~&mP#T#Z&p~&uVU~!O!P$U!Q![&j#V#W$x#X#Y$U#]#^&W#a#b$x#d#e&^~'aRS~!c!}'[#R#S'[#T#o'[",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 4, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 30
})
